import type { Project } from "../types";

/**
 * MoveSmart — AI-powered real-time exercise trainer app.
 * Screens are exported from the Figma file "All designs" (two iterations of
 * the onboarding flow plus home, exercise library and profile). Descriptions
 * of the client brief come from the designer's portfolio record; anything
 * marked as an assumption or placeholder still needs the designer's input.
 */
const img = (name: string, alt: string, caption?: string) => ({
  src: `/projects/movesmart/${name}`,
  alt,
  width: 824,
  height: 1834,
  frame: "phone" as const,
  caption,
});

export const moveSmart: Project = {
  slug: "movesmart",
  title: "MoveSmart",
  tagline: "UX and UI for an AI exercise trainer that tracks your movement and coaches your form in real time.",
  categories: ["Mobile", "UX Design", "UI Design", "Product Design"],
  type: "Mobile application · Health & fitness",
  platform: "Android & iOS",
  role: "UX design, user flow, UI design, custom icons & illustrations",
  tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator", "Canva Pro"],
  timeline: "[Timeline]",
  year: "2025",
  client: "Client project (name withheld)",
  status: "Client project",
  featured: true,
  order: 2,
  accent: "#2BE92B",
  accentSoft: "#141816",
  cover: {
    src: "/projects/movesmart/cover",
    alt: "Three refreshed MoveSmart screens on phones: home with a calorie ring, the welcome screen with posture callouts, and the exercise library",
    width: 1600,
    height: 1200,
  },
  screens: [
    img("r-home", "Refreshed MoveSmart home: greeting, a guided-session card with a Start now button, today's calorie ring with calories left and workout time, and goal cards for water and calories above a labelled tab bar", "Home — one primary action, today's progress as a ring, goals below"),
    img("r-goals", "Refreshed calories goal screen: day, week and month tabs, a large progress ring showing 1,300 of 2,150 kcal, a weekly bar chart, workout and water cards, and Edit goal and Auto-detect goal buttons", "Calories goal — progress, the week at a glance and two clear actions"),
    img("r-library", "Refreshed exercise library: search, filter chips and exercise cards for Lunges and Plank with duration, sets, level, rating and a Start button", "Exercise library — duration, sets and level before you tap Start"),
    img("r-profile-info", "Refreshed profile setup, step 2 of 3: segmented sex selector, age stepper, weight and height fields with units, and a privacy note", "Profile setup — progress, units and why the data is needed"),
    img("r-welcome", "Refreshed welcome screen: athlete silhouette with live posture and calories callouts, AI coach badge, headline and Get started button", "Welcome — the promise, shown rather than told"),
    img("r-sign-in", "Refreshed sign-in screen with labelled email and password fields, remember me, forgot password, a full-width Log in button and Google and Apple sign-in", "Sign in — labelled fields and one primary button"),
    img("r-sign-up", "Refreshed sign-up screen with full name, email and password fields, a password strength meter and a terms checkbox", "Sign up — strength meter and consent in the form"),
    img("r-profile", "Refreshed profile screen: avatar, name and email, sex, age, weight and height tiles, and a settings list with log out", "Profile — body data at a glance, settings below"),
    img("r-splash", "Refreshed splash screen with the MoveSmart logo, wordmark, tagline and a loading bar", "Splash"),
    img("r-finished", "Refreshed setup-complete screen with a success check and a summary of the profile values", "Setup complete — a summary instead of a dead end"),
  ],
  wireframes: [],
  iterations: [
    {
      title: "Home: delivered version → September 2026 refresh",
      note: "Same content, clearer hierarchy. The motivational line becomes a quiet chip, the Start card gains a label and a single orange action, activity becomes a calorie ring with what is left today, and the tab bar gets text labels and a visible active state.",
      before: img("home-v2", "Home screen as delivered to the client"),
      after: img("r-home", "Refreshed home screen"),
      beforeLabel: "Delivered",
      afterLabel: "Refresh",
    },
    {
      title: "Calories goal: delivered version → refresh",
      note: "The placeholder “Goal 2” card is replaced by water intake, the progress bar becomes a ring with the amount left, and the two grey buttons become one secondary and one primary action with icons.",
      before: img("goals", "Calories goal screen as delivered"),
      after: img("r-goals", "Refreshed calories goal screen"),
      beforeLabel: "Delivered",
      afterLabel: "Refresh",
    },
    {
      title: "Exercise library: delivered version → refresh",
      note: "Each card now answers “how long, how hard, which muscles?” before the Start button. The Lunges card also gets its own description (the delivered file reused the squats copy).",
      before: img("library-v2", "Exercise library as delivered"),
      after: img("r-library", "Refreshed exercise library"),
      beforeLabel: "Delivered",
      afterLabel: "Refresh",
    },
    {
      title: "Profile setup: delivered version → refresh",
      note: "Labels move above the fields, units are shown, “Hight” is corrected, a step indicator shows progress, and the privacy note sits where the question is asked.",
      before: img("profile-info", "Profile setup as delivered"),
      after: img("r-profile-info", "Refreshed profile setup"),
      beforeLabel: "Delivered",
      afterLabel: "Refresh",
    },
    {
      title: "Sign in: delivered version → refresh",
      note: "Placeholder-only fields become labelled fields with icons, “Forget” becomes “Forgot password?”, and the primary action spans the width so it is the obvious next step.",
      before: img("sign-in", "Sign-in screen as delivered"),
      after: img("r-sign-in", "Refreshed sign-in screen"),
      beforeLabel: "Delivered",
      afterLabel: "Refresh",
    },
    {
      title: "Home, first pass → second pass (original project)",
      note: "Version one had a single Start Exercise card and a lot of empty space. Version two, the delivered design, kept the card in place and added activity (calories burned, workout time) and today's goals (water, calories).",
      before: img("home", "First version of the home screen with only a Start Exercise card"),
      after: img("home-v2", "Second version of the home screen with activity and goal tiles"),
      beforeLabel: "Version 1",
      afterLabel: "Version 2",
    },
  ],
  overview:
    "MoveSmart is an AI-powered real-time exercise trainer: the app watches a workout through the phone camera, tracks movement and posture, and gives guidance as you go. I designed the user experience and interface for the onboarding flow (splash, welcome, login, sign-up and profile setup), the home screen, the exercise library and the user profile, then iterated the visual direction once the flow was settled. Custom icons and illustrations were produced in Photoshop, Illustrator and Canva.",
  problem: [
    "People who exercise at home rarely get feedback on their form, and generic workout videos cannot see what they are doing. The product's promise is real-time correction, so the interface has to collect a little personal data up front (age, weight, height, sex) to calibrate calorie targets, without making onboarding feel like a medical form.",
    "During a session the screen is glanced at from a distance. Anything that matters mid-workout needs to be large, high-contrast and reduced to one action.",
  ],
  research: {
    methods: [
      "Mapped the end-to-end flow before designing screens: splash → welcome → login or sign-up → profile info → ready → home → exercise → progress.",
      "Reviewed how fitness apps handle first-run data collection and how they present exercises (photo, short description, single start action).",
    ],
    assumptions: [
      "Users set the phone down 1–2 metres away during exercise, so mid-workout UI uses larger type and single actions (design assumption, not yet validated).",
      "A short, four-field profile step is acceptable when the app explains why the data is needed (the copy on the profile screen does exactly that).",
    ],
    competitive: ["[Competitive analysis] Add the apps that were reviewed and the specific takeaways."],
    findings: [
      "Every exercise card needs the same three things: a photo showing the movement, a one-line description, and one button. Anything more competes with the photo.",
      "Dark surfaces keep the focus on imagery and the accent buttons, which matters for a camera-based product.",
    ],
  },
  persona: {
    name: "The Home Exerciser",
    descriptor: "Trains at home without a coach · wants to avoid injury · motivated by daily goals",
    quote: "I never know if I'm doing lunges right. I just want something to tell me.",
    goals: ["Exercise with correct form without paying for a trainer", "Hit a daily calorie and water goal", "Keep sessions short and structured"],
    frustrations: ["Videos that cannot see what you are doing", "Long sign-up forms before any value", "Apps that bury the start button"],
    behaviours: ["Works out 3–4 times a week in a small space", "Checks goals on the home screen before and after a session"],
    basis: "Proto-persona based on the brief and design assumptions; it was not derived from user interviews.",
  },
  journey: [
    { stage: "Discover", doing: "Opens the app for the first time", thinking: "What is this and what will it do for me?", feeling: 3, opportunity: "Welcome screen states the promise in one line: AI-powered realtime exercise trainer." },
    { stage: "Sign up", doing: "Creates an account and enters profile info", thinking: "Why do you need my weight?", feeling: 2, opportunity: "Explain on the same screen that the data is used to calculate calories and give reference points." },
    { stage: "Choose", doing: "Picks an exercise from the library", thinking: "Which one, and how do I do it?", feeling: 4, opportunity: "Photo + short description + one Start now button per exercise." },
    { stage: "Train", doing: "Performs the exercise while the AI tracks posture", thinking: "Am I doing this right?", feeling: 3, opportunity: "Large, single-message feedback during the session." },
    { stage: "Review", doing: "Checks calories, workout minutes and water on the home screen", thinking: "Did I hit today's goal?", feeling: 4, opportunity: "Goal tiles on the home screen with what is left for the day." },
  ],
  ia: {
    label: "MoveSmart",
    children: [
      { label: "Onboarding", children: [{ label: "Splash" }, { label: "Welcome" }, { label: "Log in / Sign up" }, { label: "Add profile info" }, { label: "Ready" }] },
      { label: "Home", children: [{ label: "Start exercise" }, { label: "Activity & goals" }, { label: "Calories · Workout · Water" }] },
      { label: "Exercise Library", children: [{ label: "Lunges" }, { label: "Plank" }, { label: "More exercises" }] },
      { label: "Profile", children: [{ label: "Gender · Age · Weight · Height" }, { label: "Edit goals" }] },
    ],
  },
  flow: {
    title: "First run to first exercise",
    nodes: [
      { id: "start", label: "Splash → Welcome", kind: "start" },
      { id: "account", label: "Have an account?", kind: "decision" },
      { id: "signin", label: "Sign in", kind: "step" },
      { id: "signup", label: "Sign up", kind: "step" },
      { id: "profile", label: "Add profile info: age, weight, height, sex", kind: "step" },
      { id: "ready", label: "MoveSmart is ready to use", kind: "step" },
      { id: "home", label: "Home: Start Exercise", kind: "step" },
      { id: "library", label: "Exercise Library: choose Lunges / Plank", kind: "step" },
      { id: "end", label: "Live session with posture tracking", kind: "end" },
    ],
    edges: [
      { from: "start", to: "account" },
      { from: "account", to: "signin", label: "Yes" },
      { from: "account", to: "signup", label: "No" },
      { from: "signup", to: "profile" },
      { from: "profile", to: "ready" },
      { from: "ready", to: "home" },
      { from: "signin", to: "home" },
      { from: "home", to: "library" },
      { from: "library", to: "end" },
    ],
  },
  prototype: { note: "[Prototype link] Add the Figma prototype link here if one can be shared." },
  links: [{ label: "Figma file — All designs", href: "https://www.figma.com/design/xhOm00zrgeOXTOny4Kf430/All-designs" }],
  designSystem: {
    colors: [
      { name: "Ink", hex: "#0B0D0C", role: "Background" },
      { name: "Surface", hex: "#141816", role: "Cards, fields, tab bar" },
      { name: "Surface raised", hex: "#1B201D", role: "Secondary buttons, steppers" },
      { name: "Brand green", hex: "#2BE92B", role: "Primary actions, progress, active states" },
      { name: "Signal orange", hex: "#FF5A1F", role: "Start a workout, calories" },
      { name: "Violet", hex: "#9B8CFF", role: "Workout time, information" },
      { name: "Teal", hex: "#3DD6C8", role: "Water" },
      { name: "Text", hex: "#F3F6F4", role: "Headings and body" },
      { name: "Muted", hex: "#A3ACA7", role: "Labels and secondary text" },
    ],
    type: [
      { name: "Wordmark", family: "Bakbak One", size: "20–40", weight: "400", sample: "MOVESMART" },
      { name: "Display", family: "Plus Jakarta Sans", size: "28 / 34", weight: "800", sample: "Welcome back" },
      { name: "Title", family: "Plus Jakarta Sans", size: "18–20 / 26", weight: "700", sample: "Today's activity" },
      { name: "Body", family: "Plus Jakarta Sans", size: "15 / 22", weight: "400", sample: "Log in to continue your training plan." },
      { name: "Label", family: "Plus Jakarta Sans", size: "12–13 / 16", weight: "600", sample: "Step 2 of 3" },
    ],
    radius: [
      { name: "Card", value: "22px" },
      { name: "Button · field", value: "16px" },
      { name: "Chip", value: "18px" },
    ],
    notes: [
      "These are the tokens of the September 2026 refresh. The delivered file used Arial, Calistoga and Bree Serif with charcoal #222222, orange #FF4500 and blue #0A84FF; the refresh keeps the brand green and the orange start actions, and replaces the blue account buttons with the green primary so every screen has one primary colour.",
      "Touch targets are at least 44 px; text on the dark surfaces meets WCAG AA contrast.",
    ],
    theme: { primary: "#2BE92B", primaryInk: "#041204", surface: "#141816", bg: "#0B0D0C", text: "#F3F6F4", muted: "#A3ACA7", border: "#2A302C", radius: "16px", font: "inherit" },
  },
  solution: [
    "Onboarding is five short steps with one decision (log in or sign up). The profile step explains, on the same screen, that age, weight, height and sex are used to calculate calories and give reference points, so the request feels reasonable rather than intrusive.",
    "The home screen leads with a single Start Exercise card and a motivational line; the second iteration adds activity, calorie, workout-time and water goals so the screen also answers “how am I doing today?”.",
    "Each exercise in the library is a photo, one sentence and one Start now button, so choosing a movement takes a glance. Orange is reserved for exercise actions and blue for account actions, giving each type of action a consistent colour.",
    "The visual direction was iterated once the flow was stable: version two layers athlete silhouettes behind the onboarding cards to add energy without changing layout or content.",
    "In September 2026 I revisited the delivered screens and rebuilt them as a higher-fidelity set (self-initiated, not part of the client delivery): one type family, labelled form fields, a single primary colour, progress rings instead of bare bars, a labelled tab bar, and fixes for copy issues such as “Hight”, “Forget” and the placeholder “Goal 2” card. The refreshed frames sit next to the originals in the Figma file.",
  ],
  outcome: {
    measured: false,
    headline: "Delivered a consistent set of screens ready for developer handoff, with two documented visual iterations and a later high-fidelity refresh.",
    items: ["Onboarding, home, exercise library and profile screens in Figma", "Two iterations of the onboarding visuals", "Custom icon set and illustrations", "September 2026 refresh: ten redesigned screens in the same Figma file"],
    note: "No usage data is available. The next step would be moderated tests of the profile step and a live session to validate the distance-readability assumption.",
  },
  contentStatus: "partial",
  seoDescription: "Mobile UX/UI case study: MoveSmart, an AI-powered real-time exercise trainer app. Onboarding flow, exercise library, profile setup and two visual iterations and a high-fidelity refresh designed in Figma.",
};
