import type { Project } from "../types";

/**
 * Salon Control — redesign of a live salon-management web app.
 * Source: heuristic review of the live product (Sep 2026), the Figma design
 * system and the interactive HTML prototype built for the redesign.
 * Screens below are captured from that prototype.
 */
export const salonControl: Project = {
  slug: "salon-control",
  title: "Salon Control",
  shortTitle: "Salon Control",
  tagline: "Redesigning a cash-first salon management dashboard so an owner can run the day from one screen.",
  categories: ["Web", "UX Design", "UI Design", "Product Design"],
  type: "Web application · SaaS dashboard",
  platform: "Web · responsive 1440 / 1280 / 834 / 390",
  role: "UX audit, UX/UI design, design system, interactive prototype",
  tools: ["Figma", "HTML & CSS prototype"],
  timeline: "September 2026",
  year: "2026",
  client: "Live product used by a gents' salon in Dubai (concept redesign)",
  status: "Concept redesign",
  featured: true,
  order: 1,
  accent: "#0F6E56",
  accentSoft: "#E6F4EF",
  cover: {
    src: "/projects/salon-control/cover",
    alt: "Salon Control redesigned dashboard with the glass background in a browser window, with the mobile view beside it",
    width: 1600,
    height: 1200,
  },
  screens: [
    { src: "/projects/salon-control/dashboard", alt: "Redesigned dashboard on the glass background: frosted KPI cards, the live queue table, a needs-attention list and a 7-day revenue chart over a soft mint, gold and green glow", width: 2160, height: 1350, frame: "browser", caption: "Dashboard — cash, sales, queue and alerts on one screen, on the glass background" },
    { src: "/projects/salon-control/quick-sale", alt: "Quick Sale on the glass background: service tiles on the left and a compact checkout panel on the right", width: 2160, height: 1350, frame: "browser", caption: "Quick Sale — optional fields collapsed behind a disclosure" },
    { src: "/projects/salon-control/appointments", alt: "Appointments and queue screen on the glass background with status badges, filters and row actions", width: 2160, height: 1350, frame: "browser", caption: "Appointments & Queue — status is colour plus text, actions on hover" },
    { src: "/projects/salon-control/new-appointment", alt: "New appointment modal with pre-filled defaults and an inline validation error on the time field, over the blurred dashboard", width: 2160, height: 1350, frame: "browser", caption: "New appointment — a modal with sensible defaults and inline validation" },
    { src: "/projects/salon-control/customers", alt: "Customers screen on the glass background with a searchable customer book and visit history", width: 2160, height: 1350, frame: "browser", caption: "Customers — search, visits and preferences in one table" },
    { src: "/projects/salon-control/cash", alt: "Cash Closing screen on the glass background with expected versus counted cash and an approval action", width: 2160, height: 1350, frame: "browser", caption: "Cash Closing — a guided close with the reason field beside the approval" },
    { src: "/projects/salon-control/mobile-dashboard", alt: "Mobile dashboard at 390px wide on the glass background with stacked KPI cards and a bottom tab bar", width: 780, height: 1688, frame: "phone", caption: "Mobile — bottom tab bar, card rows instead of tables" },
    { src: "/projects/salon-control/mobile-quick-sale", alt: "Mobile Quick Sale on the glass background with two-column service tiles", width: 780, height: 1688, frame: "phone", caption: "Mobile Quick Sale" },
  ],
  iterations: [
    {
      title: "Dashboard: flat surfaces → glass background",
      note: "The latest version keeps every component and layout and changes the ground: a soft mint, gold and green ambient glow behind frosted cards (white at 50%, background blur 22) and a frosted header. Hierarchy comes from depth instead of borders, and text stays on at least 50% white for contrast.",
      before: { src: "/projects/salon-control/flat-dashboard", alt: "Dashboard with flat white cards on a light grey background", width: 2160, height: 1350, frame: "browser" },
      after: { src: "/projects/salon-control/dashboard", alt: "Dashboard with frosted glass cards over an ambient glow", width: 2160, height: 1350, frame: "browser" },
      beforeLabel: "Flat",
      afterLabel: "Glass",
    },
    {
      title: "Quick Sale: flat surfaces → glass background",
      note: "The same treatment carries across every screen, so the product feels like one surface. Selected service tiles keep their solid green outline so state never depends on the translucency.",
      before: { src: "/projects/salon-control/flat-quick-sale", alt: "Quick Sale with flat white cards", width: 2160, height: 1350, frame: "browser" },
      after: { src: "/projects/salon-control/quick-sale", alt: "Quick Sale with frosted glass cards", width: 2160, height: 1350, frame: "browser" },
      beforeLabel: "Flat",
      afterLabel: "Glass",
    },
  ],
  wireframes: [
    { src: "/projects/salon-control/wf-dashboard", alt: "Greyscale structural layout of the dashboard", width: 2160, height: 1350, frame: "browser", caption: "Dashboard structure — grouped sidebar, KPI row, queue + attention split (greyscale layout pass)" },
    { src: "/projects/salon-control/wf-quick-sale", alt: "Greyscale structural layout of Quick Sale", width: 2160, height: 1350, frame: "browser", caption: "Quick Sale structure — tiles left, checkout right" },
    { src: "/projects/salon-control/wf-mobile", alt: "Greyscale structural layout of the mobile dashboard", width: 780, height: 1688, frame: "phone", caption: "Mobile structure" },
  ],
  links: [{ label: "Figma file — Salon Web App UI Design", href: "https://www.figma.com/design/tETz8EhhNyPJgaLb2OCvCq" }],
  overview:
    "Salon Control is a cash-first control app for a single-branch gents' salon: quick sales, a walk-in queue, stock recipes, payroll, compliance records and a daily cash close. The live product works, but the owner has to travel through fourteen flat navigation items and long single-scroll pages to answer basic questions like “who is waiting?” and “can I close the day?”. I audited the live app, restructured its information architecture, and redesigned it on a token-based design system with a fully interactive prototype.",
  problem: [
    "The dashboard only showed finance totals. The queue, appointments, low stock and compliance alerts, which drive the owner's actual day, were buried inside modules, and a static “how it works” panel occupied prime space.",
    "Every module was a long single scroll of KPI row → form → table → form → table, with every add/edit form permanently visible. Pages were three to six screens tall, tables broke words mid-column, and destructive actions (delete, archive, reverse) had no confirmation step.",
    "The header carried nine controls at equal weight, there was no notification centre, no global record search, and on mobile the navigation collapsed into a dropdown under a header roughly 350px tall.",
  ],
  research: {
    methods: [
      "Full walkthrough of the live product logged in as the owner role, documenting every module, table, form and state (14 modules, 40+ tables and forms).",
      "Heuristic evaluation against Nielsen's ten heuristics, producing twelve prioritised findings.",
      "Task-path analysis for the three most frequent jobs: record a sale, add a walk-in or appointment, close the day.",
      "Inventory of the existing visual system (type scale, colour, spacing, radius, touch targets) to decide what to keep.",
    ],
    assumptions: [
      "The primary user is the owner or manager of a single shop who closes the cash every evening. Cashier and barber roles are secondary. This came from the role model in the product, not from interviews.",
      "Desktop is the main context for the owner; the mobile view is used for quick checks. This has not been validated with usage data.",
    ],
    competitive: [
      "No formal competitive analysis was carried out for this redesign. Layout patterns were benchmarked informally against common POS and scheduling dashboards (grouped sidebar, KPI strip, queue-first home).",
    ],
    findings: [
      "Creating an appointment took a navigation, a scroll to a permanently visible form and nine fields with no defaults for time or staff.",
      "Two accent colours (brass for active navigation, green for primary actions) competed for attention; status was communicated by text only.",
      "There was no feedback layer: a single “Saved” pill in the header stood in for toasts, inline validation and success states.",
      "Naming mixed concerns: “Clients & Queue” held appointments, “Staff & Payroll” mixed HR and payroll, and Accounting, Reports and Cash Closing overlapped.",
    ],
  },
  persona: {
    name: "The Owner-Operator",
    descriptor: "Single-branch salon owner · Dubai · manages cash, stock and staff personally",
    quote: "Before I lock the drawer I need to know what came in, what went out, and what I still owe.",
    goals: [
      "See queue, cash and alerts at a glance without opening five modules",
      "Record a sale or a walk-in in seconds while the shop is busy",
      "Close the day with confidence that stock and cash reconcile",
    ],
    frustrations: [
      "Long pages with forms that are always open",
      "Actions that delete or reverse records with no confirmation",
      "Tables that overflow on the phone he actually carries around the shop",
    ],
    behaviours: [
      "Checks the app several times a day on desktop at the counter, and on his phone between clients",
      "Delegates quick sales to a cashier but approves every cash variance himself",
    ],
    basis: "Proto-persona derived from the product's role model and task flows. It was not built from user interviews and should be validated before being treated as research.",
  },
  journey: [
    { stage: "Open the shop", doing: "Logs in, checks yesterday's close and today's bookings", thinking: "Did last night reconcile? Who is booked this morning?", feeling: 3, opportunity: "Surface pending approvals and the first appointments on the dashboard." },
    { stage: "Serve customers", doing: "Cashier records sales; walk-ins join the queue", thinking: "Who is waiting and for whom?", feeling: 2, opportunity: "A live queue on the home screen with one-tap Start / Complete." },
    { stage: "Restock & pay", doing: "Enters purchase bills and small expenses", thinking: "What is low? What do I owe suppliers?", feeling: 3, opportunity: "Low-stock and supplier-due items in a ‘needs attention’ list." },
    { stage: "Close the day", doing: "Counts cash, enters the total, explains any variance", thinking: "Does the count match? Where did the difference come from?", feeling: 2, opportunity: "A guided close with expected vs counted cash and the reason field beside the approval button." },
    { stage: "Review", doing: "Looks at weekly revenue and barber performance", thinking: "Which services and barbers are doing well?", feeling: 4, opportunity: "A 7-day revenue chart and per-barber summary without leaving the dashboard." },
  ],
  ia: {
    label: "Salon Control",
    children: [
      { label: "Overview", children: [{ label: "Dashboard", note: "Queue, cash, alerts, 7-day revenue" }] },
      { label: "Daily operations", children: [{ label: "Quick Sale" }, { label: "Appointments & Queue" }, { label: "Customers" }] },
      { label: "Catalogue & stock", children: [{ label: "Services" }, { label: "Inventory & Tools" }, { label: "Purchases" }, { label: "Expenses" }] },
      { label: "People & compliance", children: [{ label: "Staff & Payroll" }, { label: "Compliance" }] },
      { label: "Money & reports", children: [{ label: "Cash Closing" }, { label: "Accounting" }, { label: "Reports" }] },
      { label: "System", children: [{ label: "Setup" }, { label: "Settings" }] },
    ],
  },
  flow: {
    title: "Add an appointment from the dashboard",
    nodes: [
      { id: "start", label: "Dashboard", kind: "start" },
      { id: "new", label: "Tap “New” in the queue card", kind: "step" },
      { id: "modal", label: "New appointment modal opens with defaults: today, next free slot, preferred barber", kind: "step" },
      { id: "customer", label: "Existing customer?", kind: "decision" },
      { id: "pick", label: "Search & select customer", kind: "step" },
      { id: "add", label: "Add name + phone inline", kind: "step" },
      { id: "details", label: "Confirm service, barber, time, optional deposit", kind: "step" },
      { id: "valid", label: "All required fields valid?", kind: "decision" },
      { id: "error", label: "Inline error + focus moves to the field", kind: "step" },
      { id: "save", label: "Save → loading → success", kind: "step" },
      { id: "end", label: "Row appears in the live queue, toast confirms", kind: "end" },
    ],
    edges: [
      { from: "start", to: "new" },
      { from: "new", to: "modal" },
      { from: "modal", to: "customer" },
      { from: "customer", to: "pick", label: "Yes" },
      { from: "customer", to: "add", label: "No" },
      { from: "pick", to: "details" },
      { from: "add", to: "details" },
      { from: "details", to: "valid" },
      { from: "valid", to: "error", label: "No" },
      { from: "error", to: "details" },
      { from: "valid", to: "save", label: "Yes" },
      { from: "save", to: "end" },
    ],
  },
  designSystem: {
    colors: [
      { name: "Green 600", hex: "#0F6E56", role: "Primary actions, active states" },
      { name: "Green 900", hex: "#0B2620", role: "Sidebar" },
      { name: "Mint 400", hex: "#5FD3A5", role: "Accent indicator" },
      { name: "Gold 500", hex: "#C9A24D", role: "Secondary data series" },
      { name: "Neutral 900", hex: "#16211C", role: "Text" },
      { name: "Neutral 600", hex: "#5B6862", role: "Secondary text" },
      { name: "Neutral 200", hex: "#E3E7E4", role: "Borders" },
      { name: "Neutral 50", hex: "#F6F7F5", role: "Canvas" },
      { name: "Red 600", hex: "#C23A3A", role: "Error / destructive" },
      { name: "Amber 600", hex: "#B7791F", role: "Warning" },
      { name: "Blue 600", hex: "#2F6FE4", role: "Info" },
    ],
    type: [
      { name: "Page title", family: "Inter", size: "28 / 36", weight: "600", sample: "Good afternoon, Tehseem" },
      { name: "Card title", family: "Inter", size: "16 / 24", weight: "600", sample: "Today's queue & appointments" },
      { name: "Body", family: "Inter", size: "14 / 20", weight: "400", sample: "Tap services, choose the customer and barber, take payment." },
      { name: "Label", family: "Inter", size: "13 / 20", weight: "500", sample: "Expected cash today" },
      { name: "KPI value", family: "Inter · tabular", size: "26 / 34", weight: "600", sample: "AED 1,240.00" },
      { name: "Caption", family: "Inter", size: "12 / 16", weight: "400", sample: "Live · updates as customers check in" },
    ],
    radius: [
      { name: "Small", value: "6px" },
      { name: "Medium", value: "10px" },
      { name: "Large", value: "16px" },
    ],
    spacing: "4px base scale · 8 / 12 / 16 / 20 / 24 / 32",
    notes: [
      "Figma variables: 28 primitives, 32 semantic colour tokens (light mode), 9 spacing and 4 radius tokens; 16 text styles and 4 effect styles.",
      "57 icon components on a 20px grid; button set with 4 variants × 6 states, a label text property, an icon-left boolean and hover/press Smart Animate reactions.",
      "One accent instead of two: brass is demoted to a data colour, green owns every interactive element.",
      "Glass background: base gradient #EEF4F0 → #F7F6F1 with four blurred colour fields (mint, gold, green, blue); cards are white at 50% with a white 75% stroke, background blur 22 and a soft green-tinted shadow; menus are white at 82%.",
    ],
    theme: {
      primary: "#0F6E56",
      primaryInk: "#FFFFFF",
      surface: "#FFFFFF",
      bg: "#F6F7F5",
      text: "#16211C",
      muted: "#7F8A85",
      border: "#E3E7E4",
      radius: "10px",
      font: "Inter, system-ui, sans-serif",
    },
  },
  solution: [
    "The navigation is grouped into six labelled sections instead of fourteen flat items, with Setup moved to the end and a collapsible 72px icon rail for smaller screens. The header keeps only what is used constantly: global search, New sale, notifications and a profile menu.",
    "The dashboard now answers the owner's questions directly: four KPI cards, a live queue with row actions, a “needs attention” list for approvals, expiries, low stock and supplier balances, a 7-day revenue chart, payment mix and per-barber totals.",
    "Forms open on demand in modals or side panels with defaults pre-filled, validation shown inline beside the field, and a loading → success → toast sequence. Destructive actions always pass through a confirmation dialog that contains the reason field.",
    "On mobile, tables become card rows with status on the first line, a bottom tab bar replaces the dropdown, and modals become bottom sheets. Touch targets stay at or above 44px.",
    "The latest iteration changes the background of the whole app: a soft ambient glow (mint, gold, brand green and a touch of blue) behind frosted-glass cards, header and menus. It gives the dashboard depth and a calmer, more premium feel without touching layout, content or contrast. The glass screens are also built as editable frames in the Figma file.",
  ],
  outcome: {
    measured: false,
    headline: "Delivered as a concept redesign; business impact has not been measured.",
    items: [
      "15 redesigned screens, 20+ modals, dropdowns and states, plus tablet and mobile layouts",
      "Design system in Figma: variables, 16 text styles, 57 icons, component sets with states",
      "Interactive HTML prototype and a written wiring spec (timings, easing, triggers) for handoff",
      "Glass-background version of every screen, also built as editable frames in Figma",
      "47 exported frames prepared for import into the Figma file",
    ],
    note: "No usage or business metrics are claimed. The next step would be a moderated usability test of the three core tasks with the owner and cashier, and a comparison of task time against the live product.",
  },
  contentStatus: "documented",
  seoDescription:
    "UX case study: auditing and redesigning Salon Control, a salon management web app. Information architecture, dashboard design, design system with Figma variables, and an interactive prototype.",
};
